[tool.poetry]
name = "get-start-with-beam"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
apache-beam = "^2.51.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
